// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/wangfeiping/aimrocks/kepler/models"
)

// GetKeyGenReader is a Reader for the GetKeyGen structure.
type GetKeyGenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKeyGenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetKeyGenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetKeyGenOK creates a GetKeyGenOK with default headers values
func NewGetKeyGenOK() *GetKeyGenOK {
	return &GetKeyGenOK{}
}

/*GetKeyGenOK handles this case with default header values.

OK
*/
type GetKeyGenOK struct {
	Payload *models.TypesResult
}

func (o *GetKeyGenOK) Error() string {
	return fmt.Sprintf("[GET /key/gen][%d] getKeyGenOK  %+v", 200, o.Payload)
}

func (o *GetKeyGenOK) GetPayload() *models.TypesResult {
	return o.Payload
}

func (o *GetKeyGenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TypesResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
