// Code generated by go-swagger; DO NOT EDIT.

package key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetKeyGenParams creates a new GetKeyGenParams object
// with the default values initialized.
func NewGetKeyGenParams() *GetKeyGenParams {

	return &GetKeyGenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKeyGenParamsWithTimeout creates a new GetKeyGenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKeyGenParamsWithTimeout(timeout time.Duration) *GetKeyGenParams {

	return &GetKeyGenParams{

		timeout: timeout,
	}
}

// NewGetKeyGenParamsWithContext creates a new GetKeyGenParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetKeyGenParamsWithContext(ctx context.Context) *GetKeyGenParams {

	return &GetKeyGenParams{

		Context: ctx,
	}
}

// NewGetKeyGenParamsWithHTTPClient creates a new GetKeyGenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKeyGenParamsWithHTTPClient(client *http.Client) *GetKeyGenParams {

	return &GetKeyGenParams{
		HTTPClient: client,
	}
}

/*GetKeyGenParams contains all the parameters to send to the API endpoint
for the get key gen operation typically these are written to a http.Request
*/
type GetKeyGenParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get key gen params
func (o *GetKeyGenParams) WithTimeout(timeout time.Duration) *GetKeyGenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get key gen params
func (o *GetKeyGenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get key gen params
func (o *GetKeyGenParams) WithContext(ctx context.Context) *GetKeyGenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get key gen params
func (o *GetKeyGenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get key gen params
func (o *GetKeyGenParams) WithHTTPClient(client *http.Client) *GetKeyGenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get key gen params
func (o *GetKeyGenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetKeyGenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
