// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ModuleApplyQsc module apply qsc
// swagger:model module.ApplyQsc
type ModuleApplyQsc struct {

	// banker pub
	BankerPub string `json:"bankerPub,omitempty"`

	// create time
	CreateTime string `json:"createTime,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// info
	Info string `json:"info,omitempty"`

	// note
	Note string `json:"note,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`

	// qos chain Id
	QosChainID string `json:"qosChainId,omitempty"`

	// qsc name
	QscName string `json:"qscName,omitempty"`

	// qsc pub
	QscPub string `json:"qscPub,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`

	// update time
	UpdateTime string `json:"updateTime,omitempty"`
}

// Validate validates this module apply qsc
func (m *ModuleApplyQsc) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModuleApplyQsc) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModuleApplyQsc) UnmarshalBinary(b []byte) error {
	var res ModuleApplyQsc
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
