// Code generated by go-swagger; DO NOT EDIT.

package qcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/wangfeiping/aimrocks/kepler/models"
)

// GetQcpApplyReader is a Reader for the GetQcpApply structure.
type GetQcpApplyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQcpApplyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetQcpApplyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetQcpApplyOK creates a GetQcpApplyOK with default headers values
func NewGetQcpApplyOK() *GetQcpApplyOK {
	return &GetQcpApplyOK{}
}

/*GetQcpApplyOK handles this case with default header values.

OK
*/
type GetQcpApplyOK struct {
	Payload *models.ModuleApplyQcp
}

func (o *GetQcpApplyOK) Error() string {
	return fmt.Sprintf("[GET /qcp/apply][%d] getQcpApplyOK  %+v", 200, o.Payload)
}

func (o *GetQcpApplyOK) GetPayload() *models.ModuleApplyQcp {
	return o.Payload
}

func (o *GetQcpApplyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModuleApplyQcp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
