// Code generated by go-swagger; DO NOT EDIT.

package qcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/wangfeiping/aimrocks/kepler/models"
)

// GetQcpCaApplyIDReader is a Reader for the GetQcpCaApplyID structure.
type GetQcpCaApplyIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQcpCaApplyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetQcpCaApplyIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetQcpCaApplyIDOK creates a GetQcpCaApplyIDOK with default headers values
func NewGetQcpCaApplyIDOK() *GetQcpCaApplyIDOK {
	return &GetQcpCaApplyIDOK{}
}

/*GetQcpCaApplyIDOK handles this case with default header values.

OK
*/
type GetQcpCaApplyIDOK struct {
	Payload *models.TypesResult
}

func (o *GetQcpCaApplyIDOK) Error() string {
	return fmt.Sprintf("[GET /qcp/ca/{applyId}][%d] getQcpCaApplyIdOK  %+v", 200, o.Payload)
}

func (o *GetQcpCaApplyIDOK) GetPayload() *models.TypesResult {
	return o.Payload
}

func (o *GetQcpCaApplyIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TypesResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
