// Code generated by go-swagger; DO NOT EDIT.

package qcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetQcpApplyParams creates a new GetQcpApplyParams object
// with the default values initialized.
func NewGetQcpApplyParams() *GetQcpApplyParams {
	var ()
	return &GetQcpApplyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetQcpApplyParamsWithTimeout creates a new GetQcpApplyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetQcpApplyParamsWithTimeout(timeout time.Duration) *GetQcpApplyParams {
	var ()
	return &GetQcpApplyParams{

		timeout: timeout,
	}
}

// NewGetQcpApplyParamsWithContext creates a new GetQcpApplyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetQcpApplyParamsWithContext(ctx context.Context) *GetQcpApplyParams {
	var ()
	return &GetQcpApplyParams{

		Context: ctx,
	}
}

// NewGetQcpApplyParamsWithHTTPClient creates a new GetQcpApplyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetQcpApplyParamsWithHTTPClient(client *http.Client) *GetQcpApplyParams {
	var ()
	return &GetQcpApplyParams{
		HTTPClient: client,
	}
}

/*GetQcpApplyParams contains all the parameters to send to the API endpoint
for the get qcp apply operation typically these are written to a http.Request
*/
type GetQcpApplyParams struct {

	/*Email
	  邮箱

	*/
	Email string
	/*Phone
	  手机号

	*/
	Phone string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get qcp apply params
func (o *GetQcpApplyParams) WithTimeout(timeout time.Duration) *GetQcpApplyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get qcp apply params
func (o *GetQcpApplyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get qcp apply params
func (o *GetQcpApplyParams) WithContext(ctx context.Context) *GetQcpApplyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get qcp apply params
func (o *GetQcpApplyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get qcp apply params
func (o *GetQcpApplyParams) WithHTTPClient(client *http.Client) *GetQcpApplyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get qcp apply params
func (o *GetQcpApplyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the get qcp apply params
func (o *GetQcpApplyParams) WithEmail(email string) *GetQcpApplyParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the get qcp apply params
func (o *GetQcpApplyParams) SetEmail(email string) {
	o.Email = email
}

// WithPhone adds the phone to the get qcp apply params
func (o *GetQcpApplyParams) WithPhone(phone string) *GetQcpApplyParams {
	o.SetPhone(phone)
	return o
}

// SetPhone adds the phone to the get qcp apply params
func (o *GetQcpApplyParams) SetPhone(phone string) {
	o.Phone = phone
}

// WriteToRequest writes these params to a swagger request
func (o *GetQcpApplyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param email
	qrEmail := o.Email
	qEmail := qrEmail
	if qEmail != "" {
		if err := r.SetQueryParam("email", qEmail); err != nil {
			return err
		}
	}

	// query param phone
	qrPhone := o.Phone
	qPhone := qrPhone
	if qPhone != "" {
		if err := r.SetQueryParam("phone", qPhone); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
