// Code generated by go-swagger; DO NOT EDIT.

package qcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetQcpCaApplyIDParams creates a new GetQcpCaApplyIDParams object
// with the default values initialized.
func NewGetQcpCaApplyIDParams() *GetQcpCaApplyIDParams {
	var ()
	return &GetQcpCaApplyIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetQcpCaApplyIDParamsWithTimeout creates a new GetQcpCaApplyIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetQcpCaApplyIDParamsWithTimeout(timeout time.Duration) *GetQcpCaApplyIDParams {
	var ()
	return &GetQcpCaApplyIDParams{

		timeout: timeout,
	}
}

// NewGetQcpCaApplyIDParamsWithContext creates a new GetQcpCaApplyIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetQcpCaApplyIDParamsWithContext(ctx context.Context) *GetQcpCaApplyIDParams {
	var ()
	return &GetQcpCaApplyIDParams{

		Context: ctx,
	}
}

// NewGetQcpCaApplyIDParamsWithHTTPClient creates a new GetQcpCaApplyIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetQcpCaApplyIDParamsWithHTTPClient(client *http.Client) *GetQcpCaApplyIDParams {
	var ()
	return &GetQcpCaApplyIDParams{
		HTTPClient: client,
	}
}

/*GetQcpCaApplyIDParams contains all the parameters to send to the API endpoint
for the get qcp ca apply ID operation typically these are written to a http.Request
*/
type GetQcpCaApplyIDParams struct {

	/*ApplyID
	  申请ID

	*/
	ApplyID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get qcp ca apply ID params
func (o *GetQcpCaApplyIDParams) WithTimeout(timeout time.Duration) *GetQcpCaApplyIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get qcp ca apply ID params
func (o *GetQcpCaApplyIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get qcp ca apply ID params
func (o *GetQcpCaApplyIDParams) WithContext(ctx context.Context) *GetQcpCaApplyIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get qcp ca apply ID params
func (o *GetQcpCaApplyIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get qcp ca apply ID params
func (o *GetQcpCaApplyIDParams) WithHTTPClient(client *http.Client) *GetQcpCaApplyIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get qcp ca apply ID params
func (o *GetQcpCaApplyIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplyID adds the applyID to the get qcp ca apply ID params
func (o *GetQcpCaApplyIDParams) WithApplyID(applyID int64) *GetQcpCaApplyIDParams {
	o.SetApplyID(applyID)
	return o
}

// SetApplyID adds the applyId to the get qcp ca apply ID params
func (o *GetQcpCaApplyIDParams) SetApplyID(applyID int64) {
	o.ApplyID = applyID
}

// WriteToRequest writes these params to a swagger request
func (o *GetQcpCaApplyIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param applyId
	if err := r.SetPathParam("applyId", swag.FormatInt64(o.ApplyID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
