// Code generated by go-swagger; DO NOT EDIT.

package qcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostQcpApplyReader is a Reader for the PostQcpApply structure.
type PostQcpApplyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostQcpApplyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostQcpApplyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostQcpApplyOK creates a PostQcpApplyOK with default headers values
func NewPostQcpApplyOK() *PostQcpApplyOK {
	return &PostQcpApplyOK{}
}

/*PostQcpApplyOK handles this case with default header values.

OK
*/
type PostQcpApplyOK struct {
	Payload int64
}

func (o *PostQcpApplyOK) Error() string {
	return fmt.Sprintf("[POST /qcp/apply][%d] postQcpApplyOK  %+v", 200, o.Payload)
}

func (o *PostQcpApplyOK) GetPayload() int64 {
	return o.Payload
}

func (o *PostQcpApplyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
