// Code generated by go-swagger; DO NOT EDIT.

package qcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutQcpApplyParams creates a new PutQcpApplyParams object
// with the default values initialized.
func NewPutQcpApplyParams() *PutQcpApplyParams {
	var ()
	return &PutQcpApplyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutQcpApplyParamsWithTimeout creates a new PutQcpApplyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutQcpApplyParamsWithTimeout(timeout time.Duration) *PutQcpApplyParams {
	var ()
	return &PutQcpApplyParams{

		timeout: timeout,
	}
}

// NewPutQcpApplyParamsWithContext creates a new PutQcpApplyParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutQcpApplyParamsWithContext(ctx context.Context) *PutQcpApplyParams {
	var ()
	return &PutQcpApplyParams{

		Context: ctx,
	}
}

// NewPutQcpApplyParamsWithHTTPClient creates a new PutQcpApplyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutQcpApplyParamsWithHTTPClient(client *http.Client) *PutQcpApplyParams {
	var ()
	return &PutQcpApplyParams{
		HTTPClient: client,
	}
}

/*PutQcpApplyParams contains all the parameters to send to the API endpoint
for the put qcp apply operation typically these are written to a http.Request
*/
type PutQcpApplyParams struct {

	/*ID
	  申请ID

	*/
	ID int64
	/*Status
	  状态 1发放证书 2申请无效

	*/
	Status int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put qcp apply params
func (o *PutQcpApplyParams) WithTimeout(timeout time.Duration) *PutQcpApplyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put qcp apply params
func (o *PutQcpApplyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put qcp apply params
func (o *PutQcpApplyParams) WithContext(ctx context.Context) *PutQcpApplyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put qcp apply params
func (o *PutQcpApplyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put qcp apply params
func (o *PutQcpApplyParams) WithHTTPClient(client *http.Client) *PutQcpApplyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put qcp apply params
func (o *PutQcpApplyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put qcp apply params
func (o *PutQcpApplyParams) WithID(id int64) *PutQcpApplyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put qcp apply params
func (o *PutQcpApplyParams) SetID(id int64) {
	o.ID = id
}

// WithStatus adds the status to the put qcp apply params
func (o *PutQcpApplyParams) WithStatus(status int64) *PutQcpApplyParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the put qcp apply params
func (o *PutQcpApplyParams) SetStatus(status int64) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *PutQcpApplyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := swag.FormatInt64(qrID)
	if qID != "" {
		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	// query param status
	qrStatus := o.Status
	qStatus := swag.FormatInt64(qrStatus)
	if qStatus != "" {
		if err := r.SetQueryParam("status", qStatus); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
