// Code generated by go-swagger; DO NOT EDIT.

package qcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutQcpApplyIDParams creates a new PutQcpApplyIDParams object
// with the default values initialized.
func NewPutQcpApplyIDParams() *PutQcpApplyIDParams {
	var ()
	return &PutQcpApplyIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutQcpApplyIDParamsWithTimeout creates a new PutQcpApplyIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutQcpApplyIDParamsWithTimeout(timeout time.Duration) *PutQcpApplyIDParams {
	var ()
	return &PutQcpApplyIDParams{

		timeout: timeout,
	}
}

// NewPutQcpApplyIDParamsWithContext creates a new PutQcpApplyIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutQcpApplyIDParamsWithContext(ctx context.Context) *PutQcpApplyIDParams {
	var ()
	return &PutQcpApplyIDParams{

		Context: ctx,
	}
}

// NewPutQcpApplyIDParamsWithHTTPClient creates a new PutQcpApplyIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutQcpApplyIDParamsWithHTTPClient(client *http.Client) *PutQcpApplyIDParams {
	var ()
	return &PutQcpApplyIDParams{
		HTTPClient: client,
	}
}

/*PutQcpApplyIDParams contains all the parameters to send to the API endpoint
for the put qcp apply ID operation typically these are written to a http.Request
*/
type PutQcpApplyIDParams struct {

	/*ID
	  申请ID

	*/
	ID int64
	/*Status
	  状态 1发放证书 2申请无效

	*/
	Status int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put qcp apply ID params
func (o *PutQcpApplyIDParams) WithTimeout(timeout time.Duration) *PutQcpApplyIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put qcp apply ID params
func (o *PutQcpApplyIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put qcp apply ID params
func (o *PutQcpApplyIDParams) WithContext(ctx context.Context) *PutQcpApplyIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put qcp apply ID params
func (o *PutQcpApplyIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put qcp apply ID params
func (o *PutQcpApplyIDParams) WithHTTPClient(client *http.Client) *PutQcpApplyIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put qcp apply ID params
func (o *PutQcpApplyIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put qcp apply ID params
func (o *PutQcpApplyIDParams) WithID(id int64) *PutQcpApplyIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put qcp apply ID params
func (o *PutQcpApplyIDParams) SetID(id int64) {
	o.ID = id
}

// WithStatus adds the status to the put qcp apply ID params
func (o *PutQcpApplyIDParams) WithStatus(status int64) *PutQcpApplyIDParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the put qcp apply ID params
func (o *PutQcpApplyIDParams) SetStatus(status int64) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *PutQcpApplyIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// query param status
	qrStatus := o.Status
	qStatus := swag.FormatInt64(qrStatus)
	if qStatus != "" {
		if err := r.SetQueryParam("status", qStatus); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
