// Code generated by go-swagger; DO NOT EDIT.

package qcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/wangfeiping/aimrocks/kepler/models"
)

// PutQcpApplyReader is a Reader for the PutQcpApply structure.
type PutQcpApplyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutQcpApplyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutQcpApplyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutQcpApplyOK creates a PutQcpApplyOK with default headers values
func NewPutQcpApplyOK() *PutQcpApplyOK {
	return &PutQcpApplyOK{}
}

/*PutQcpApplyOK handles this case with default header values.

OK
*/
type PutQcpApplyOK struct {
	Payload *models.TypesResult
}

func (o *PutQcpApplyOK) Error() string {
	return fmt.Sprintf("[PUT /qcp/apply][%d] putQcpApplyOK  %+v", 200, o.Payload)
}

func (o *PutQcpApplyOK) GetPayload() *models.TypesResult {
	return o.Payload
}

func (o *PutQcpApplyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TypesResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
