// Code generated by go-swagger; DO NOT EDIT.

package qcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutQcpApplyIDReader is a Reader for the PutQcpApplyID structure.
type PutQcpApplyIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutQcpApplyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutQcpApplyIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutQcpApplyIDOK creates a PutQcpApplyIDOK with default headers values
func NewPutQcpApplyIDOK() *PutQcpApplyIDOK {
	return &PutQcpApplyIDOK{}
}

/*PutQcpApplyIDOK handles this case with default header values.

OK
*/
type PutQcpApplyIDOK struct {
	Payload int64
}

func (o *PutQcpApplyIDOK) Error() string {
	return fmt.Sprintf("[PUT /qcp/apply/{id}][%d] putQcpApplyIdOK  %+v", 200, o.Payload)
}

func (o *PutQcpApplyIDOK) GetPayload() int64 {
	return o.Payload
}

func (o *PutQcpApplyIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
