// Code generated by go-swagger; DO NOT EDIT.

package qsc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/wangfeiping/aimrocks/kepler/models"
)

// GetQscApplyReader is a Reader for the GetQscApply structure.
type GetQscApplyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQscApplyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetQscApplyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetQscApplyOK creates a GetQscApplyOK with default headers values
func NewGetQscApplyOK() *GetQscApplyOK {
	return &GetQscApplyOK{}
}

/*GetQscApplyOK handles this case with default header values.

OK
*/
type GetQscApplyOK struct {
	Payload *models.ModuleApplyQsc
}

func (o *GetQscApplyOK) Error() string {
	return fmt.Sprintf("[GET /qsc/apply][%d] getQscApplyOK  %+v", 200, o.Payload)
}

func (o *GetQscApplyOK) GetPayload() *models.ModuleApplyQsc {
	return o.Payload
}

func (o *GetQscApplyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModuleApplyQsc)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
