// Code generated by go-swagger; DO NOT EDIT.

package qsc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostQscApplyParams creates a new PostQscApplyParams object
// with the default values initialized.
func NewPostQscApplyParams() *PostQscApplyParams {
	var ()
	return &PostQscApplyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostQscApplyParamsWithTimeout creates a new PostQscApplyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostQscApplyParamsWithTimeout(timeout time.Duration) *PostQscApplyParams {
	var ()
	return &PostQscApplyParams{

		timeout: timeout,
	}
}

// NewPostQscApplyParamsWithContext creates a new PostQscApplyParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostQscApplyParamsWithContext(ctx context.Context) *PostQscApplyParams {
	var ()
	return &PostQscApplyParams{

		Context: ctx,
	}
}

// NewPostQscApplyParamsWithHTTPClient creates a new PostQscApplyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostQscApplyParamsWithHTTPClient(client *http.Client) *PostQscApplyParams {
	var ()
	return &PostQscApplyParams{
		HTTPClient: client,
	}
}

/*PostQscApplyParams contains all the parameters to send to the API endpoint
for the post qsc apply operation typically these are written to a http.Request
*/
type PostQscApplyParams struct {

	/*BankerPub
	  用于接收联盟币的账户公钥

	*/
	BankerPub string
	/*Email
	  邮箱

	*/
	Email string
	/*Info
	  申请说明

	*/
	Info string
	/*Phone
	  手机号

	*/
	Phone string
	/*QosChainID
	  公链ChainId

	*/
	QosChainID string
	/*QscName
	  联盟币名称

	*/
	QscName string
	/*QscPub
	  QSC公钥

	*/
	QscPub string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post qsc apply params
func (o *PostQscApplyParams) WithTimeout(timeout time.Duration) *PostQscApplyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post qsc apply params
func (o *PostQscApplyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post qsc apply params
func (o *PostQscApplyParams) WithContext(ctx context.Context) *PostQscApplyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post qsc apply params
func (o *PostQscApplyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post qsc apply params
func (o *PostQscApplyParams) WithHTTPClient(client *http.Client) *PostQscApplyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post qsc apply params
func (o *PostQscApplyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBankerPub adds the bankerPub to the post qsc apply params
func (o *PostQscApplyParams) WithBankerPub(bankerPub string) *PostQscApplyParams {
	o.SetBankerPub(bankerPub)
	return o
}

// SetBankerPub adds the bankerPub to the post qsc apply params
func (o *PostQscApplyParams) SetBankerPub(bankerPub string) {
	o.BankerPub = bankerPub
}

// WithEmail adds the email to the post qsc apply params
func (o *PostQscApplyParams) WithEmail(email string) *PostQscApplyParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the post qsc apply params
func (o *PostQscApplyParams) SetEmail(email string) {
	o.Email = email
}

// WithInfo adds the info to the post qsc apply params
func (o *PostQscApplyParams) WithInfo(info string) *PostQscApplyParams {
	o.SetInfo(info)
	return o
}

// SetInfo adds the info to the post qsc apply params
func (o *PostQscApplyParams) SetInfo(info string) {
	o.Info = info
}

// WithPhone adds the phone to the post qsc apply params
func (o *PostQscApplyParams) WithPhone(phone string) *PostQscApplyParams {
	o.SetPhone(phone)
	return o
}

// SetPhone adds the phone to the post qsc apply params
func (o *PostQscApplyParams) SetPhone(phone string) {
	o.Phone = phone
}

// WithQosChainID adds the qosChainID to the post qsc apply params
func (o *PostQscApplyParams) WithQosChainID(qosChainID string) *PostQscApplyParams {
	o.SetQosChainID(qosChainID)
	return o
}

// SetQosChainID adds the qosChainId to the post qsc apply params
func (o *PostQscApplyParams) SetQosChainID(qosChainID string) {
	o.QosChainID = qosChainID
}

// WithQscName adds the qscName to the post qsc apply params
func (o *PostQscApplyParams) WithQscName(qscName string) *PostQscApplyParams {
	o.SetQscName(qscName)
	return o
}

// SetQscName adds the qscName to the post qsc apply params
func (o *PostQscApplyParams) SetQscName(qscName string) {
	o.QscName = qscName
}

// WithQscPub adds the qscPub to the post qsc apply params
func (o *PostQscApplyParams) WithQscPub(qscPub string) *PostQscApplyParams {
	o.SetQscPub(qscPub)
	return o
}

// SetQscPub adds the qscPub to the post qsc apply params
func (o *PostQscApplyParams) SetQscPub(qscPub string) {
	o.QscPub = qscPub
}

// WriteToRequest writes these params to a swagger request
func (o *PostQscApplyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param bankerPub
	qrBankerPub := o.BankerPub
	qBankerPub := qrBankerPub
	if qBankerPub != "" {
		if err := r.SetQueryParam("bankerPub", qBankerPub); err != nil {
			return err
		}
	}

	// query param email
	qrEmail := o.Email
	qEmail := qrEmail
	if qEmail != "" {
		if err := r.SetQueryParam("email", qEmail); err != nil {
			return err
		}
	}

	// query param info
	qrInfo := o.Info
	qInfo := qrInfo
	if qInfo != "" {
		if err := r.SetQueryParam("info", qInfo); err != nil {
			return err
		}
	}

	// query param phone
	qrPhone := o.Phone
	qPhone := qrPhone
	if qPhone != "" {
		if err := r.SetQueryParam("phone", qPhone); err != nil {
			return err
		}
	}

	// query param qosChainId
	qrQosChainID := o.QosChainID
	qQosChainID := qrQosChainID
	if qQosChainID != "" {
		if err := r.SetQueryParam("qosChainId", qQosChainID); err != nil {
			return err
		}
	}

	// query param qscName
	qrQscName := o.QscName
	qQscName := qrQscName
	if qQscName != "" {
		if err := r.SetQueryParam("qscName", qQscName); err != nil {
			return err
		}
	}

	// query param qscPub
	qrQscPub := o.QscPub
	qQscPub := qrQscPub
	if qQscPub != "" {
		if err := r.SetQueryParam("qscPub", qQscPub); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
