// Code generated by go-swagger; DO NOT EDIT.

package qsc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutQscApplyIDReader is a Reader for the PutQscApplyID structure.
type PutQscApplyIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutQscApplyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutQscApplyIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutQscApplyIDOK creates a PutQscApplyIDOK with default headers values
func NewPutQscApplyIDOK() *PutQscApplyIDOK {
	return &PutQscApplyIDOK{}
}

/*PutQscApplyIDOK handles this case with default header values.

OK
*/
type PutQscApplyIDOK struct {
	Payload int64
}

func (o *PutQscApplyIDOK) Error() string {
	return fmt.Sprintf("[PUT /qsc/apply/{id}][%d] putQscApplyIdOK  %+v", 200, o.Payload)
}

func (o *PutQscApplyIDOK) GetPayload() int64 {
	return o.Payload
}

func (o *PutQscApplyIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
