// Code generated by go-swagger; DO NOT EDIT.

package qsc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutQscApplyIDParams creates a new PutQscApplyIDParams object
// with the default values initialized.
func NewPutQscApplyIDParams() *PutQscApplyIDParams {
	var ()
	return &PutQscApplyIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutQscApplyIDParamsWithTimeout creates a new PutQscApplyIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutQscApplyIDParamsWithTimeout(timeout time.Duration) *PutQscApplyIDParams {
	var ()
	return &PutQscApplyIDParams{

		timeout: timeout,
	}
}

// NewPutQscApplyIDParamsWithContext creates a new PutQscApplyIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutQscApplyIDParamsWithContext(ctx context.Context) *PutQscApplyIDParams {
	var ()
	return &PutQscApplyIDParams{

		Context: ctx,
	}
}

// NewPutQscApplyIDParamsWithHTTPClient creates a new PutQscApplyIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutQscApplyIDParamsWithHTTPClient(client *http.Client) *PutQscApplyIDParams {
	var ()
	return &PutQscApplyIDParams{
		HTTPClient: client,
	}
}

/*PutQscApplyIDParams contains all the parameters to send to the API endpoint
for the put qsc apply ID operation typically these are written to a http.Request
*/
type PutQscApplyIDParams struct {

	/*ID
	  申请ID

	*/
	ID int64
	/*Status
	  状态 1发放证书 2申请无效

	*/
	Status int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put qsc apply ID params
func (o *PutQscApplyIDParams) WithTimeout(timeout time.Duration) *PutQscApplyIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put qsc apply ID params
func (o *PutQscApplyIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put qsc apply ID params
func (o *PutQscApplyIDParams) WithContext(ctx context.Context) *PutQscApplyIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put qsc apply ID params
func (o *PutQscApplyIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put qsc apply ID params
func (o *PutQscApplyIDParams) WithHTTPClient(client *http.Client) *PutQscApplyIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put qsc apply ID params
func (o *PutQscApplyIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put qsc apply ID params
func (o *PutQscApplyIDParams) WithID(id int64) *PutQscApplyIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put qsc apply ID params
func (o *PutQscApplyIDParams) SetID(id int64) {
	o.ID = id
}

// WithStatus adds the status to the put qsc apply ID params
func (o *PutQscApplyIDParams) WithStatus(status int64) *PutQscApplyIDParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the put qsc apply ID params
func (o *PutQscApplyIDParams) SetStatus(status int64) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *PutQscApplyIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// query param status
	qrStatus := o.Status
	qStatus := swag.FormatInt64(qrStatus)
	if qStatus != "" {
		if err := r.SetQueryParam("status", qStatus); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
